update project.yaml, docker-compose, checkFilters script
subquery/airdrop-subql-project pull request #2
Opened 2023-07-04 02:47 UTC by lamcc21

- update contract sdk
- add docker-compose, project.yaml
- update script

2023-07-04 03:16 UTC, ianhe8x commented on project-kepler.yaml
> +    version: '>2.8.0'
doesn't seems this project rely on api.getNetwork

2023-07-04 03:16 UTC, ianhe8x commented on project-kepler.yaml
> +    version: '>2.8.0'
```suggestion
    version: '*'
```

2023-07-04 03:17 UTC, ianhe8x commented on project-testnet.yaml
> +    version: '>2.8.0'
```suggestion
    version: '*'
```

2023-07-04 03:19 UTC, ianhe8x requested changes

2023-07-04 03:19 UTC, ianhe8x commented on project-testnet.yaml
> +  startBlock: 33168664
need to update this to the new height

2023-07-04 04:02 UTC, mzxyz commented on project-testnet.yaml
> +      address: '0xB64D73B96358855075576D66746D2a88e043CC1E'
Update the airdrop contract address: `0xdE4c8a50A8AFC4BcB9250Df8f4d61C8eBF98F535`

2023-07-11 03:43 UTC, ianhe8x approved these changes

2023-07-11 03:44 UTC, merged